### PR TITLE
Update report.sh

### PR DESCRIPTION
**Pull request by mth309**
Fixed the parsing for when a self test is in progress on a SAS device.  The previous code was colorizing both lastTestHours and lastTestStatus as critical while the test was running due to parsing the wrong fields.

### CODE REVIEW

**Comment by dak180** [comment]
@mth309 That is a great description; it should be the commit message.

**Comment by mth309** [comment]
Looks like I forgot the commit description field when uploading this morning. Would you like me to update it?

**Comment by mth309** [comment]
I think I figured out that when I'm using GitHub Desktop and push my changes to my forked repo, it doesn't ask me to add any comment to the commit.  It's just a single button click "push to master" and it uploads my local changes to GitHub.  So the only opportunity I have at that point to add a description is when I issue you a pull request.  Also from some research it seems I can't change the commit comment after the fact using the Web UI.  It seems like it can be done from a command line, but that's not how I'm interacting with GitHub.

**Comment by dak180** [comment]
> I think I figured out that when I'm using GitHub Desktop and push my changes to my forked repo, it doesn't ask me to add any comment to the commit. It's just a single button click "push to master" and it uploads my local changes to GitHub. So the only opportunity I have at that point to add a description is when I issue you a pull request.

@mth309 see https://idratherbewriting.com/learnapidoc/pubapis_github_desktop_client.html for a reasonable flow; my guess is the `Update <filename>` is a default set to be used automatically. I would suggest turning this off; it does not really convey any useful info about a commit and if it is not auto filled it will then force you to write something before commiting.

**Pull request closed without merging**
